'use strict';

const ErrorCode = Object.freeze({
  ANALYZER_LOW_CONFIDENCE: 'ANALYZER_LOW_CONFIDENCE',
  MISSING_REQUIRED_BOUNDARY: 'MISSING_REQUIRED_BOUNDARY',
  DIMENSION_RULE_INVALID: 'DIMENSION_RULE_INVALID',
  RENDER_FAILED: 'RENDER_FAILED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  LOCK_MISSING: 'LOCK_MISSING',
  IMAGE_GENERATION_FAILED: 'IMAGE_GENERATION_FAILED'
});

module.exports = {
  ErrorCode
};
